device: 'cuda'
model: 'adversarial_model'
dataset: 'iam_word'
seed: 123456
img_height: 32
char_width: 16
ckpt: './data/weights/FW-GAN.pth'

training:
  dset_split: 'trnval'
  epochs: 100
  lr_policy: 'linear'
  start_decay_epoch: 35
  n_epochs_decay: 65
  batch_size: 8
  eval_batch_size: 6
  sample_nrow: 3
  lr: 2.0e-4
  adam_b1: 0.5
  adam_b2: 0.999
  lambda_kl: 0.0001
  sample_iter_val: 200
  print_iter_val: 20
  start_save_epoch_val: 30
  save_epoch_val: 1
  sample_dir: 'imgs'
  ckpt_dir: 'ckpts'
  lexicon: './data/english_words.txt'
  max_word_len: 20
  n_class: 81
  capitalize_ratio: 0.5
  sort_input: false
  num_critic_train: 4

valid:
  n_generate: ~
  dset_name: 'iam_word_org'
  dset_split: 'test'
  batch_size: 8
  dims: 2048
  mmd_degree: 3
  mmd_gamma: ~
  mmd_coef0: 1.
  mmd_subsets: 50
  mmd_subset_size: 1000
  mmd_var: true

test:
  interp_num: 7
  nrow: 4

GenModel:
  G_ch: 64
  style_dim: 128
  bottom_width: 4
  bottom_height: 4
  resolution: 32
  G_kernel_size: 3
  G_attn: '64'
  n_class: 81
  num_G_SVs: 1
  num_G_SV_itrs: 1
  G_shared: false
  shared_dim: 0
  no_hier: false
  cross_replica: false
  mybn: false
  BN_eps: 1.e-05
  SN_eps: 1.e-08
  init: 'N02'
  G_param: 'SN'
  norm_style: 'bn'
  bn_linear: 'SN'
  input_nc: 1
  one_hot: true
  first_layer: true
  one_hot_k: 1

DiscModel:
  D_ch: 64
  D_wide: true
  resolution: 32
  D_kernel_size: 3
  D_attn: '64'
  n_class: 81
  num_D_SVs: 1
  num_D_SV_itrs: 1
  SN_eps: 1.e-08
  output_dim: 1
  init: 'N02'
  D_param: 'SN'
  bn_linear: 'SN'
  input_nc: 1
  one_hot: true

HFDiscModel:
  D_ch: 64
  D_wide: true
  resolution: 32
  D_kernel_size: 3
  D_attn: '64'
  n_class: 81
  num_D_SVs: 1
  num_D_SV_itrs: 1
  SN_eps: 1.e-08
  output_dim: 1
  init: 'N02'
  D_param: 'SN'
  bn_linear: 'SN'
  input_nc: 1
  one_hot: true

OcrModel:
  resolution: 16
  in_channel: 1
  norm: 'bn'
  init: 'none'
  dropout: 0.
  # ctc config
  n_class: 81
  rnn_depth: 0
  bidirectional: False

SharedBackbone:
  resolution: 16
  max_dim: 256
  in_channel: 1
  dropout: 0.0
  norm: 'bn'

EncModel:
  style_dim: 96
  init: 'none'

WidModel:
  n_writer: 339
  init: 'none'